version: '3.8'
services:
  db:
    image: postgres:15
    container_name: course_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: course_adminer
    ports:
      - "8085:8080"
    depends_on:
      - db

volumes:
  db_data: